### ISSUE TITLE
Unable to setup the bot properly.

### ISSUE THREAD

**Issue by k3rokami** [freedomofkeima/messenger-maid-chan#15]
I've tried to setup the bot but it failed any idea whats wront with it? Also for the VERIFY_TOKEN where could i get it?I know this might be a old thread so you might not reply.Hope you can help.Thanks.

Here's the error.

(venv) honghongleong@honghongleong-VirtualBox:~/messenger-maid-chan$ maidchan
Traceback (most recent call last):
  File "/home/honghongleong/messenger-maid-chan/venv/bin/maidchan", line 11, in <module>
    load_entry_point('messenger-maid-chan==0.2', 'console_scripts', 'maidchan')()
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/messenger_maid_chan-0.2-py3.7.egg/maidchan/cmds/main.py", line 134, in main
    application.chatbot = ChatBotDriver(STORAGE_ADAPTER)
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/messenger_maid_chan-0.2-py3.7.egg/maidchan/chatbot.py", line 19, in __init__
    storage_adapter=storage_adapter
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/chatterbot/chatterbot.py", line 44, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/chatterbot/utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/chatterbot/storage/mongodb.py", line 97, in __init__
    self.client.admin.command({'setParameter': 1, 'internalQueryExecMaxBlockingSortBytes': 44040192})
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/pymongo/database.py", line 611, in command
    read_preference) as (sock_info, slave_ok):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1099, in _socket_for_reads
    server = topology.select_server(read_preference)
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/home/honghongleong/messenger-maid-chan/venv/lib/python3.7/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

**Comment by freedomofkeima** [comment]
Hi,

Thanks for your interest in trying this project out, I haven't touched it for quite a while but I hope this answer could help you in solving your errors.

```
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

This error is generated by `chatterbot`, since [Chatterbot](https://chatterbot.readthedocs.io/en/stable/storage/) requires either `SQLStorageAdapter` or  `MongoDatabaseAdapter`. This project itself is using MongoDB so you need to have it installed. ([Step 4 in the documentation](https://messenger-maid-chan.readthedocs.io/en/latest/setup.html)). If you're wondering whether the application can run without `Chatterbot`, you can try configuring `IS_CHATTERBOT_ENABLED = False` in the `config.py` file.

> Also for the VERIFY_TOKEN where could i get it?

In order to create your own Facebook bot, you can generate your own `VERIFY_TOKEN` and set it on Facebook application console `https://developers.facebook.com/apps/{YOUR_APP_ID}/webhooks/`. Ref: [Facebook documentation](https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup/#steps)

I haven't maintained this project for quite a while, for time being, I've added your Facebook ID `honghongleong` to the allowed user list, please check it out :)

Caveat: the chatbot feature is quite _broken_ right now

**Comment by k3rokami** [comment]
Hi,
Thanks for replying. I've disabled the chatterbot and it's still the same error.I guess It should be the verify token which  is causing this. This is my first time creating a messenger bot so i might not understand much.  

Edit:I've got verify token to work on localhost now gonna try to get it on to heroku.
Edit again: Can't seemed to get heroku working not the bot 😭I'll prob try again tmr since i have sch tmr.

**Comment by freedomofkeima** [comment]
> Edit again: Can't seemed to get heroku working not the bot 😭I'll prob try again tmr since i have sch tmr.

By not working, do you mean you don't receive any callback messages from Facebook or does Facebook return a `Forbidden` error message? As far as I can recall, it takes quite a while to change webhook URL to be applied.

>  I've added your Facebook ID honghongleong to the allowed user list, ...

By the way, you need to accept the invitation first at https://developers.facebook.com/requests/.

**Comment by k3rokami** [comment]
> > Edit again: Can't seemed to get heroku working not the bot 😭I'll prob try again tmr since i have sch tmr.
> 
> By not working, do you mean you don't receive any callback messages from Facebook or does Facebook return a `Forbidden` error message? As far as I can recall, it takes quite a while to change webhook URL to be applied.
> 
> > I've added your Facebook ID honghongleong to the allowed user list, ...
> 
> By the way, you need to accept the invitation first at https://developers.facebook.com/requests/.

I’ve accept the invitation, thanks for that.I’m currently having troubles having it to deploy to heroku using CLI since I used git push heroku master and there isn’t a .git folder there.I’ve also tried to upload the files to github and tried to deploy which is also a failure 😔As for not the bot won’t work since verify token is still on localhost.

**Comment by freedomofkeima** [comment]
For testing with localhost, I recommend you to use https://ngrok.com/ so that you can expose your `localhost` with `https` endpoint to the public.

For the heroku problem, I'm not sure with no `.git` folder problem as this project itself should have `.git` on the root directory. I personally deployed this project on my own VPS so I might not understand your problem well enough.

**Comment by k3rokami** [comment]
Alright I’ll try https://ngrok.com when i reach home since I’m in school now I can’t do much.

**Comment by k3rokami** [comment]
![VirtualBox_Ubuntu_28_01_2020_15_50_58](https://user-images.githubusercontent.com/50738510/73244992-26f38b00-41e6-11ea-9127-6ebfd6fc0e07.png)

I still can't get the bot to work after getting the webhook on ngrok completed.😔Hope is something I did wrong.

**Comment by freedomofkeima** [comment]
I'm not sure if I understand it correctly, but you're currently running `maidchan` in port `9999` while you're running `messenger-webhook` via `node index.js` in port `1337`. `ngrok` itself will forward port `1337` traffic to the internet.

On the bottom right screenshot, `WEBHOOK_VERIFIED` is shown, which means, Facebook has successfully triggered your `/webhook` endpoint (as shown in `ngrok` via `GET /webhook 200 OK`). This is a correct behavior.

Could you elaborate what did you do and what kind of results are you expecting?

**Comment by k3rokami** [comment]
I'm trying to get the bot up and running and it doesn't seem to be replying.I'm currently clueless on how to get it up and running.Do i have to forward maidchan port or something? :/

**Comment by freedomofkeima** [comment]
I assume you can send messages to get some responses from `messenger-webhook` already?

In that case, you only need to start `maidchan` on the specified port (by default it's `9999`, e.g.: you can change it to `4040` so that it matches with your ngrok specification) or you can use `ngrok` in port `9999` instead of `4040`.

**Comment by k3rokami** [comment]
> I assume you can send messages to get some responses from `messenger-webhook` already?
> 
> In that case, you only need to start `maidchan` on the specified port (by default it's `9999`, e.g.: you can change it to `4040` so that it matches with your ngrok specification) or you can use `ngrok` in port `9999` instead of `4040`.

I'm trying to use port 9999,btw do you have discord?If yes do you have time to chat there so we don't have to spam here.XD Also Thanks for your help until now even if it doesn't work.

Discord: honghongleong#8172

**Comment by freedomofkeima** [comment]
> Discord: honghongleong#8172

Okay added 👍
